spring.application.name: "ratings-data-service"
server.port: 8083

eureka:
  instance:
    ipAddress: 127.0.0.1
list:
   values: 1,2,3
my:
  map: "{config:'ksdfljaj',user:'asdfsdf'}"
db:
  connection: "{url:'asfdsfsd'}"
  host: host
  port: 44

spring.profiles.active: qa

spring.config.import: "configserver:"
spring.cloud.config.uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"