name: Build movie-info-service

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: cd movie-info-service && mvn -B clean package
      
    - name: Copy the jar file into a temp directory
      run: mkdir temp && cp movie-info-service/target/*.jar temp
      
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
       name: movie-info-service
       path: temp